Update token.mdx with code examples
nftlabs/portal pull request #12
Opened 2022-01-24 16:41 UTC by alionline

Hello guys,

can you please review and let me know if there is something wrong/missing?

2022-01-25 05:40 UTC, nachoiacovino requested changes
contracts -> modules

we should use async/await for everything from now on.

Also, can you pull from main and fix the conflicts?

2022-01-25 05:40 UTC, nachoiacovino commented on learn/code-examples/token/token.mdx
> +const tokenAddress = "<TOKEN_CONTRACT_ADDRESS";
```suggestion
const tokenAddress = "<TOKEN_MODULE_ADDRESS>";
```

this goes for everything "contract" -> "module"

2022-01-30 15:34 UTC, alionline commented on learn/code-examples/token/token.mdx
> +const tokenAddress = "<TOKEN_CONTRACT_ADDRESS";
hey i processed the feedback, can you please check again ?

2022-02-01 14:03 UTC, nachoiacovino commented
Fixed on commit https://github.com/nftlabs/portal/commit/472635536c826b32c1f8f6f9e68ece6b80f2a11d

2022-02-01 14:03 UTC, closed without merging