nft collection module description
nftlabs/portal pull request #21
Opened 2022-01-26 20:47 UTC by razacodespython

2022-01-26 21:27 UTC, nachoiacovino requested changes
we can delete the thumbnail, this should be moved to learn/modules

A lot of links to fix and the code is not functional.

Missing navigation (since it's part of learn), and modify navigation of previous (modules) and next (pack) pages.

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +3. To setup your local dev environment, click [here](/portal/guides/sdk-guide).
Let's add navigation at the end here (prev next) and modify the navigation of the modules and pack component too to reflect it

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +const UseModule = () => {
```suggestion
export const useModule = () => {
```

hooks should use camelCase and we can export directly here instead of importing default

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +export default UseModule
```suggestion

```

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +If you don’t know what **ipfs** is, click here.
missing a link here

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +If you’re looking for a module that can mint multiple NFTs based on the same image or music file, check out our `Bundle Collection` module here.
missing link

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +Perhaps you’re looking to efficiently create and distribute 10k pfp style collections, then check out our `Bundle Drop` module.
missing link

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +tags: [nft, module, sdk]
```suggestion
```

no tags

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +---
wrong folder, this needs to be inside learn/modules folder

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +2. List an NFT for sale on a Marketplace (you would also need the `Marketplace` module for this)
missing link (can be to /guides/marketplace for now)

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +  return nftModule;
this is undefined, is it nftModule or nftCollectionModule?

```suggestion
  return nftCollection;
```

I prefer `nftCollection`rather than any of those two. We shouldn't call it `nftModule`anymore and `nftCollectionModule`is too long

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +  const nftCollectionModule = useMemo(() => {
```suggestion
  const nftModule = useMemo(() => {
```

2022-01-26 21:27 UTC, nachoiacovino commented on guides/nft-collection/nft-collection.mdx
> +image: "./thumbnail.png"
no thumbnail needed either, this is not a guide, it's part of learn

2022-01-27 12:09 UTC, razacodespython commented on guides/nft-collection/nft-collection.mdx
> +2. List an NFT for sale on a Marketplace (you would also need the `Marketplace` module for this)
no link intended, but added one

2022-01-27 13:32 UTC, merged