connect to blockchain guide for the init sdk
nftlabs/portal pull request #56
Opened 2022-02-03 18:04 UTC by razacodespython

2022-02-03 21:42 UTC, nachoiacovino requested changes
this feels like it should be on learn instead of being a guide?

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +---
```suggestion

```

why are we using dividers here? can we get rid of all of them?

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +Make sure you have the packages installed. `npm install @3rdweb/sdk` for js and `pip install thirdweb-sdk` for python.
```suggestion
Make sure you have the packages installed. `npm install @3rdweb/sdk` for JavaScript or TypeScript and `pip install thirdweb-sdk` for Python.
```

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +nft_module_address = "0xD9bC403529471515F16DA32eee652c0a6cEcBA78";
```suggestion
const nftModuleAddress = "0xD9bC403529471515F16DA32eee652c0a6cEcBA78";
```

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +nft_module_address = "0xD9bC403529471515F16DA32eee652c0a6cEcBA78";
camelCase

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +const nft = sdk.getNFTModule(nft_module_address);
```suggestion
const nft = sdk.getNFTModule(nftModuleAddress);
```

2022-02-03 21:42 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +sdk.set_private_key("PRIVATE_KEY")
```suggestion
sdk.set_private_key(PRIVATE_KEY)
```

variable call not string

2022-02-04 10:35 UTC, razacodespython commented
I see your point.
for now I would leave it here and then depending on the coming changes with portal, we can move it.

2022-02-04 19:18 UTC, nachoiacovino requested changes
let's move this under `learn/connect-to-blockchain`

2022-02-04 19:18 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +
```suggestion
```

2022-02-04 19:18 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +---
```suggestion
---
```

delete all of the dividers under each title

2022-02-04 19:18 UTC, nachoiacovino commented on guides/connect-to-blockchain/connect-to-blockchain.mdx
> +sdk = ThirdwebSdk(SdkOptions(), network)
where is `SdkOptions()* coming from?

shouldn't we also import `ThirdwebSdk`?

2022-02-07 18:23 UTC, merged